### ISSUE TITLE
Bad comment for return value of SntpGetTime_t

### ISSUE THREAD

**Issue by machta** [FreeRTOS/coreSNTP#100]
The doc comment for `SntpGetTime_t` says "@return `true` if ...":
https://github.com/FreeRTOS/coreSNTP/blob/40d914a9a970916a0429d25b13696fad60f80758/source/include/core_sntp_client.h#L104

But the function returns `void`:  https://github.com/FreeRTOS/coreSNTP/blob/40d914a9a970916a0429d25b13696fad60f80758/source/include/core_sntp_client.h#L107

But it doesn't seem like a bad idea. Is there really no way to idicate failure from `SntpGetTime_t` or from `SntpSetTime_t`?

**Comment by kar-rahul-aws** [comment]
Hi @machta 
Thank you for reporting the issue. 
Yes, as you mentioned since both `SntpGetTime_t` and `SntpSetTime_t` internally call `clock_gettime` and `clock_settime` which have a return type , it is possible to define them as [this](https://github.com/FreeRTOS/coreSNTP/blob/main/source/include/core_sntp_client.h#L89)

But since this will be a breaking change for the applications which use this library, we are removing the comment in this [PR ](https://github.com/FreeRTOS/coreSNTP/pull/101)and will add this to our queue to improve later. You can also always contribute to the library ! We shall be happy to review it.

Thanks and Regards,
Rahul.
