### ISSUE TITLE
Log format specifier for 64-bit unsigned integer uses %lu causing issues when long unsigned is not 64-bits

### ISSUE THREAD

**Issue by warasilapm** [FreeRTOS/coreSNTP#76]
In the code below, the log format specifier explicitly expects a type of `%lu` when printing the seconds delta:

https://github.com/FreeRTOS/coreSNTP/blob/3cb8ad937f70516cb9f08a7d622cfa9195736d3b/source/core_sntp_client.c#L795C1-L798C63

This can cause unexpected formatting function behavior depending on the platform. In our case, it printed out wildly large numbers; this will be different for every implementation of the formatter.

One potential solution would be to use `inttypes.h` or simply to use `%llu`. However, for many embedded builds of the standard library, proper support of `%llu` is spotty, so this may simply be a lost cause. Perhaps a conversion to `uint32_t` would be more suitable instead?

**Comment by Skptak** [comment]
Hey, thanks for bringing this issue up! The issue you're raising here is definitely a valid one. I'll reach back out when I've had a chance to try a few different options and can figure out which may be the most portable.

**Comment by aggarg** [comment]
None of the solution is perfect but may be adding a cast to `unsigned long` is a good compromise.

**Comment by Skptak** [comment]
Apologies for the long delay in "fixing" this issue in PR #81 .
While swapping to `%llu` would be ideal, it is not a C90 Compliant modifier. Due to this a decision was made to convert the 64bit millisecond value to seconds, and cast it as a `(unsigned long)` to reduce the change of this value being too large.

This was in favor of adding additional code to check if the value would overflow the `%lu` specifier, as it would require a server response delay of over 24, or 48, days depending on if a signed or unsigned value.

I'm a bit curious to know if maybe the issue you had seen was actually due to a print statement that was incorrectly casting a `int64_t` to an ( unsigned long ) in the log, as seen [here](https://github.com/FreeRTOS/coreSNTP/pull/81/files#r1428448502)

If you feel that the fix in #81 is inadequate please feel free to open another PR, thanks!

**Comment by warasilapm** [comment]
LGTM.

I'm pretty sure there was a disconnect between the size of fields in the va_args vs. the formatter reading the format specifier that caused our issue. This should be a plenty sufficient fix. Thanks!
